# Generated by Django 4.0.1 on 2022-01-22 14:14

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=200)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=200)),
                ('birth_day', models.DateTimeField()),
                ('join_date', models.DateField(auto_now_add=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.upload_file)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=users.models.upload_file_background)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('website', models.URLField(blank=True, max_length=4000, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=2000, null=True)),
                ('birthPlace', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'No Married')], max_length=1400, null=True)),
                ('facebookAccount', models.URLField(blank=True, max_length=2000, null=True)),
                ('twitterAccount', models.URLField(blank=True, max_length=2000, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
