# Generated by Django 4.0.1 on 2022-01-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='background_image',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='image',
            new_name='user_image',
        ),
    ]
