# Generated by Django 4.0.1 on 2022-01-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_background_image_users_background_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='background',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_image',
            new_name='image',
        ),
    ]
