# Generated by Django 3.2.7 on 2022-01-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_latestorderview_latestview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestview',
            name='order',
        ),
        migrations.RemoveField(
            model_name='latestview',
            name='user',
        ),
        migrations.DeleteModel(
            name='LatestOrderView',
        ),
        migrations.DeleteModel(
            name='LatestView',
        ),
    ]
