# Generated by Django 3.2.7 on 2022-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220126_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.CharField(default='Washington, USA', max_length=2000),
        ),
    ]
