# Generated by Django 3.2.7 on 2022-01-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_orderdetailfollowing_orderfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailfollowing',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.orderfollowing'),
        ),
    ]
