# Generated by Django 3.2.7 on 2022-01-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_orderdetailfollowing_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
