# Generated by Django 3.2.7 on 2022-01-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_users_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_main_name',
            field=models.CharField(default='car', max_length=200),
            preserve_default=False,
        ),
    ]
