# Generated by Django 3.2.7 on 2022-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_users_user_main_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_main_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
