# Generated by Django 3.2.7 on 2022-02-01 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_remove_users_user_main_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=200)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=200)),
                ('birth_day', models.DateTimeField()),
                ('join_date', models.DateField(auto_now_add=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.upload_file)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=users.models.upload_file_background)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('website', models.URLField(blank=True, max_length=4000, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=2000, null=True)),
                ('birthPlace', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'No Married')], max_length=1400, null=True)),
                ('facebookAccount', models.URLField(blank=True, max_length=2000, null=True)),
                ('twitterAccount', models.URLField(blank=True, max_length=2000, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetailfollowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderfollowing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
