# Generated by Django 3.2.7 on 2022-02-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latestUser', to='users.profile')),
            ],
        ),
    ]
