# Generated by Django 3.2.7 on 2022-02-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_searchviewuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchviewuser',
            name='total_search',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
