# Generated by Django 3.2.7 on 2022-02-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220205_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchvieworder',
            name='total_follower',
        ),
        migrations.AddField(
            model_name='searchvieworderdetail',
            name='total_follower',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
