# Generated by Django 3.2.7 on 2022-02-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20220205_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchvieworderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='searchvieworderdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='SearchViewOrder',
        ),
        migrations.DeleteModel(
            name='SearchViewOrderDetail',
        ),
    ]
