# Generated by Django 3.2.7 on 2022-02-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_viewusersearchorder_viewusersearchorderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewusersearchorder',
            name='total_view',
        ),
        migrations.AddField(
            model_name='viewusersearchorderdetail',
            name='total_view',
            field=models.IntegerField(default=0),
        ),
    ]
