# Generated by Django 3.2.7 on 2022-02-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220209_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewusersearchorderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='viewusersearchorderdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='ViewUserSearchOrder',
        ),
        migrations.DeleteModel(
            name='ViewUserSearchOrderDetail',
        ),
    ]
