# Generated by Django 3.2.7 on 2022-02-12 08:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_profile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=users.models.upload_file_background),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to=users.models.upload_file),
        ),
    ]
