# Generated by Django 3.2.7 on 2022-03-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_bestsearchuserorder_bestsearchuserorderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestsearchuserorderdetail',
            name='best_order',
        ),
        migrations.RemoveField(
            model_name='bestsearchuserorderdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='BestSearchUserOrder',
        ),
        migrations.DeleteModel(
            name='BestSearchUserOrderDetail',
        ),
    ]
