# Generated by Django 3.2.7 on 2022-01-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGN', '0002_rename_total_follower_messageorder_total_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
