# Generated by Django 3.2.7 on 2022-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGN', '0005_auto_20220201_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment')], max_length=120)),
                ('description', models.TextField()),
            ],
        ),
    ]
