# Generated by Django 3.2.7 on 2022-02-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_is_active'),
        ('MGN', '0007_auto_20220201_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationfollower',
            name='user_following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Followuser', to='users.profile'),
        ),
    ]
