# Generated by Django 3.2.7 on 2022-02-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGN', '0008_notificationfollower_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationfollower',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
