# Generated by Django 3.2.7 on 2022-02-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGN', '0009_notificationfollower_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationfollower',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
