# Generated by Django 3.2.7 on 2022-02-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGN', '0010_notificationfollower_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationfollower',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notificationfollower',
            name='subject',
        ),
    ]
