# Generated by Django 3.2.7 on 2022-02-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGN', '0014_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
