# Generated by Django 3.2.7 on 2022-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGN', '0015_activity_activity_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
